## Migrate bundled CRB fixtures to the versionless Cerebro R6 class.
##
## Run from the package root after devtools::load_all(".").  The script copies
## only public data fields onto fresh objects, so serialized method bindings are
## generated by the current class instead of preserved from the legacy object.

migrate_cerebro_object <- function(object) {
  stopifnot(is.environment(object), inherits(object, "R6"))

  migrated <- Cerebro$new()
  for (field in names(Cerebro$public_fields)) {
    if (exists(field, envir = object, inherits = FALSE)) {
      migrated[[field]] <- object[[field]]
    }
  }
  migrated
}

migrate_bundled_cerebro_objects <- function(
  example_dir = "inst/extdata/examples"
) {
  files <- list.files(example_dir, pattern = "[.]crb$", full.names = TRUE)
  for (path in files) {
    original <- readRDS(path)
    migrated <- migrate_cerebro_object(original)
    stopifnot(inherits(migrated, "Cerebro"), inherits(migrated, "R6"))

    temporary <- tempfile(
      pattern = paste0(basename(path), "."),
      tmpdir = dirname(path)
    )
    saveRDS(migrated, temporary)
    verified <- readRDS(temporary)
    stopifnot(inherits(verified, "Cerebro"), inherits(verified, "R6"))
    file.rename(temporary, path)
  }
  invisible(files)
}
